apiVersion: v1
kind: Service
metadata:
  name: sentinelmesh-aggregator
spec:
  selector:
    app: sentinelmesh-aggregator
  ports:
    - name: http
      port: {{ .Values.aggregator.service.port }}
      targetPort: 9480
